### ISSUE TITLE
quoteParty.partySubIdOrTypeId column should not have FK constraint to partyIdentifierType table

### ISSUE THREAD

**Issue by bushjames** [mojaloop/quoting-service#284]
The subIdOrTypeId of a quote/transfer party should not be limited to values of the enum partyIdentifierType. This field is intended to carry an enum value OR an identifier itself. The foreign key that exists between quoteParty.partySubIdOrTypeId and the partyIdentifierType table forbids an identifier value being used. This constraint should be removed to allow compliance with usecases that do not use identifier type enums.

**Comment by elnyry-sam-k** [comment]
Definitely @bushjames (both values should be allowed and shouldn't be limited to the partyIdentifier enum values)..

**Comment by mdebarros** [comment]
Hey @bushjames, are you in the process of fixing this, or should we create an issue for the Core-OSS team?

**Comment by mdebarros** [comment]
> Please can you create an issue for the Core-OSS team @mdebarros . Many thanks.

Issue created --> https://github.com/mojaloop/project/issues/2506
