### ISSUE TITLE
List of known issues in quoting-service as of v6.3.0-snapshot Release

### ISSUE THREAD

**Issue by elnyry** [mojaloop/quoting-service#9]
**Description**:
Below is the list of known issues in _quoting-service_ given by Mowali along with the quoting-service itself which is now adopted into the Mojaloop Open Source space and is in snapshot-phase (There are still a few standardizations left to be done to make a normal release). Below is the overview of the bug followed by expected behavior. 

**List of Issues / Bugs**:
1. Sending quote with amount zero: not showing any error
    - Payer DFSP initiates the request sending
      - ID of the Payee DFSP. MSISDN of the Payee
      - Amount to be transfer with Zero value.
      - Amount TypeCurrency
    - The quote response should have:
      - Validate the Amount to be transfer
      - Error displayed due to a Zero amount to be transfer: "You can not make a transfer with zero amount, please enter a valid amount"
      - No quote should be created
2. Send Quote Request: Validate Currency Field
  2.a Sending a Quote with empty Currency field - Not showing any error
  2.b POST/quotes - Quote is created using an invalid currency - No Error 5106 is shown
    - Payer DFSP initiates the request sending:
       - ID of the Payee DFSP
       - MSISDN of the Payee
       - Amount to be transfer with Zero value
       - Amount Type
       - Currency field empty
     - The quote response should:
       - Validate that all the fields are completed
       - If the currency field is empty should show an error: "You have to complete all the fields to initiate a quote request"
       - No quote should be created
3. Sending a quote with negative Amount - not showing error
    - Payer DFSP initiates the request sending:
       - ID of the Payee DFSP
       - MSISDN of the Payee
       - Amount to be transfer with negative value
       - Amount Type
       - Currency
     - The quote response should:
       - Validate the Amount to be transfer
       - Error displayed due to a Zero amount to be transfer: "You can not make a transfer with a negative amount, please enter a valid amount"
       - No quote should be created
4. Send Quote Request: Validate Quote Id Field
  4.a POST/quotes Sending quote with malformed quote id not returning Error 3101 Malformed Syntax
  4.b PUT/quotes - Callback is send with different Quote ID than the one in POST/quotes - Not a bug
  4.c GET/Quotes - QuoteId not found error 3205 not displayed
    - The quote response should:
       - Validate the quote Id and return response code 404 in case the quoteId is malformed
       - Error Code 3001
       - Error displayed: "Malformed Syntax quoteId".
       - No quote should be created
5. Send Quote Request: Validate Syntax Information 
  5.a POST/quotes Sending quote with invalid TransactionID Or Payee partyIdType Or Payer partyIdType
  5.b POST/Quotes sending invalid payeePartyIdentifier OR payerPartyIdentifier in quote should return error 3101
  5.c Error: POST/quotes request (Error in createQuoteError: Error: ER_NO_SUCH_TABLE: Table 'central_ledger.quoteerror' doesn't exist    at Query.Sequence._packetToError)
  5.d POST/quotes Sending quote with invalid TransactionID Or Payee partyIdType Or Payer partyIdType
    - The quote response should:
       - Validate the information and return response code 404 in case the following fields are malformed: 
         - TransactionID
         - PayeepartyIdType
         - PayerpartyIdType 
         - payeePartyIdentifier
         - payerPartyIdentifier
       - Error code: 3101
       - Error displayed: "Malformed Syntax"
       - No quote should be created
6. Send Quote Request - 06- Validate Information Type Syntax
  6.a Send a Quote request with malformed content type
  6.b POST/Quotes - Sending a quote with invalid transaction type field - No Error 5101 is shown
    - The quote response should:
       - Validate the information and return response code 406 in case the following informations is malformed: 
         - Content Type
       - Error code: 3101
       - Error displayed: "Malformed Syntax"
       - No quote should be created
7. POST/Quotes Sending quote with any missing mandatory fields: quoteid, transactionid, payer partyIdType, payee partyIdType, payer partyIdentifier, payee partyIdentifier error not displayed correctly
    - The quote response should:
      - Validate the information and return response code 404 in case the following informations is missing: 
        - quoteid
        - transactionid
        - payer partyIdType
        - payee partyIdType
        - payeePartyIdentifier
        - payerPartyIdentifier
       - Error Code: 3107
       - Error description displayed: "Missing mandatory extension parameter"
       - No quote should be created
8. POST/Quotes - sending duplicate quoteid request with modified data is not returning error 3106
    - The quote response should:
      - Validate the information and return response code 404 in case the quoteId used is the same 
      - Error Code 3106
      - Error description displayed: "The quoteId is not valid for this request"
      - No quote should be created
9. POST/Quotes Not showing Error 3201 Destination FSP cannot be found
    - The quote response should:
    - Validate the information and return response code 404 in case the FSPID is incorrect
    - Error Code 3201
    - Error description displayed: "Destination FSP cannot be found"
    - No quote should be created
10. POST/Quotes - sending quote with non-existent payeePartyIdentifier - Party Not found Error code 3204
    - The quote response should:
      - Validate the information and return response code 404 in case the payeePartyIdentifier doesn't exists.
      - Error Code 3204
      - Error description displayed: "Party Not found"
      - No quote should be created
11. PUT/Quote - sending callback without condition field
    - Sending a PUT/quotes with no condition field should give an error message notifying about the missing information
12. Send Quote Request -13 - Validate the expire time with duplicate quote ID
  12.a Sending Duplicate Quote ID after expiry time - Not showing error
  12.b Sending Duplicate Quote ID within expiry time - Not showing error
    - Sending a POST/quote with correct body and headers.
      - There should successful quote.
      - Send a new quote using the same QuoteID as in step 1
      - An error due quote ID duplication should appear.
13. Get Quotes: Validate Header
  13.a GET/Quotes - Missing Accept header - Not showing Response code 400
  13.b GET/Quotes - Missing FSPIOP-Source header - Not showing Response code 400
  13.c GET/Quotes - Missing Date header - Not showing Response code 400
    - Get /quotes request with errors in the header 
    - The request should be rejected giving 400 response code and error code and error msg in the response body.
14. POST/quotes - Sending quote with incorrect version - not showing response code 406
    - Send in Post /quotes endpoint a not supported version in Switch, that call should response:
      - Validate the version in header and return a response code 406
      - Error Code 3001
      - Error Description displayed: " Unacceptable version requested"

**Comment by elnyry** [comment]
Following up on #1 - #14 as of **v7.4.2 Snapshot**
1. #1 I think is not a bug, we need to stick to the regex from the API Definition for Amounts that allows a zero (pattern: ```^([0]|([1-9][0-9]{0,17}))([.][0-9]{0,3}[1-9])?$```).
2. Schema validations specified in the API Spec are now applied here, that should take care of till #7 on the list and possibly #11 (@gibaros please confirm #11) . 
3. We'll follow-up the rest once we're good with these updates..

**Comment by elnyry** [comment]
Issue - https://github.com/mojaloop/project/issues/990 is continuation to this to address the remaining (or most of the rest) issues..

**Comment by amarmodus** [comment]
verifying and validating all issues in https://github.com/mojaloop/project/issues/1170.
During the analysis, identified following is not a bug 
5.b POST/Quotes sending invalid payeePartyIdentifier OR payerPartyIdentifier in quote should return error 3101 - 3101 is not expected and also this validation should be part of the payee and hence the error will be passed by the switch. this can be removed from the API collection as part of 971 story

**Comment by amarmodus** [comment]
10. POST/Quotes - sending quote with non-existent payeePartyIdentifier - Party Not found Error code 3204 - 3204 is not expected from switch and also this validation should be part of the payee and hence the error will be passed by the switch. this can be removed from the API collection as part of 971 story

**Comment by amarmodus** [comment]
All issues mentioned here are validated/verified/justified as part of https://github.com/mojaloop/project/issues/1170.
